### PR TITLE
remove * from tps placeholder

### PR DESCRIPTION
**Pull request by Xytrizareal**

### CODE REVIEW

**Comment by Andre601** [comment]
You are aware that the * is added in the TPSFormatter, right?

Also, it exists to indicate TPS being above 20, so removing it seems pointless.

**Comment by Xytrizareal** [comment]
oh i wasn't aware

**Comment by Xytrizareal** [comment]
ill change the code soon

**Comment by Xytrizareal** [comment]
no need i just realized

**Pull request closed without merging**
