### PR TITLE
Added 3 new placeholders

### PR DESCRIPTION
**Pull request by HexedHero**
Added:
- Total Chunks loaded
- Total Living Entities loaded
- Total Entities (Including living) loaded

### CODE REVIEW

**Comment by aBo0oDyy** [comment]
Why you're using `startsWith()` and `equals()` instead of adding it in the switch case though? Since you're not getting any argument/input from the placeholder.

**Comment by HexedHero** [comment]
Then why isn't the ram one in the case switch?

**Comment by aBo0oDyy** [comment]
I don't know, and i actually haven't noticed it before to move it to the switch case. Will do later (or if you want to do it).

**Comment by aBo0oDyy** [comment]
Thanks for your contribution.

**Pull request merged**
